### ISSUE TITLE
openvoice how to install in a shared hosting (linux)

### ISSUE THREAD

**Issue by inquba** [openvoice/openvoice#2]
HI
thanks for share the great openvoice app I need to install on my own shared hosting could you tell me the exactly proccess to install OPENVOICE in my personal Hosting company ?

the tutorial that already exists is for app engine or other for using with freeSwitch and at this time I dont have freeswitch

and I dont want any of them and I want to install the openvoice RoR rubyonrails version and add local phones and config my own sip providers

if you could detail and if have a video tutorial much better. I saw one in youtube but dont tell how to install but the features of openvoice

thanks for all and thanks for this great app
Inqub

thanks for any help with the greates opevoice

**Comment by zlu** [comment]
Have you read the README?  It is here: https://github.com/openvoice/openvoice
The self-hosted choice is not for appengine.  It also doesn't assume you have FreeSwitch installed.
